custom-datasource:
  schema: training
  driver-class-name: org.postgresql.Driver
  database-host: ${DATABASE_HOST:localhost}
  init-sql:
  database-port: ${DATABASE_PORT:5432}
  database-name: ${DATABASE_NAME:training}
  username: ${SPRING_DATASOURCE_USERNAME:postgres}
  password: ${SPRING_DATASOURCE_PASSWORD:password}
  connection-timeout: ${CUSTOM_DATASOURCE_CONNECTION_TIMEOUT:30000}
  idle-timeout: ${CUSTOM_DATASOURCE_IDLE_TIMEOUT:60000}
  maximum-pool-size: ${CUSTOM_DATASOURCE_MAXIMUM_POOL_SIZE:8}
  minimum-idle-size: ${CUSTOM_DATASOURCE_MINIMUM_IDLE_SIZE:8}
  max-lifetime: ${CUSTOM_DATASOURCE_MAX_LIFETIME:570000}
  env-url: ${SPRING_DATASOURCE_URL:}

spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'